### ISSUE TITLE
wrapper does not throw error when consequences are missing from VCF

### ISSUE THREAD

**Issue by agilly** [hmgu-itg/burden_testing#1]
When a VCF file that does not contain the consequences or LoF fields is given as an argument to `Burden_testing.pl`, no filtering occurs at all. Instead of throwing an error, the `--loftee` argument results in all variants irrespective of their consequences to be included in the burden test.

**Comment by DSuveges** [comment]
Now this problem is fixed: if variant selection based on the loftee prediction is requested, but the LoF_conf tag is missing from the vcf file, the perl script exits.
