### ISSUE TITLE
Inconsistent gene naming in group file

### ISSUE THREAD

**Issue by agilly** [hmgu-itg/burden_testing#8]
If the list of genes contains gene symbols in `make-group-file`, the output sometimes contains the ENSID, not the gene symbol. Example input file:
```
ABCG1
ADARB1
```

Output file:

```
ABCG1   21      42201695        G       A       1
ENSG00000197381 21      45133681        AGGTGTGTGCCCGACGGTGTGTGCGACCGATGGGTGTATGCTCGACAGTGGTGTGTGCGCCCACCG      A       1
```

**Comment by andrei-barysenka** [comment]
after a re-run, couldn't be reproduced, probably was caused by an early version of the pipeline
