### ISSUE TITLE
Eigen phred scores

### ISSUE THREAD

**Issue by loof91** [hmgu-itg/burden_testing#9]
Hi

I am trying to use your interesting pipeline, but when running the prepare_regions.sh script I can't download the Eigen scores.
Using axel nothing happens. If I switch to wget I get "Operation timed out". Do you have any suggestions, or could the scores be made available elsewhere?

Best
Peter

**Comment by agilly** [comment]
Solved, this was a configuration issue on our server. Please note that the b37 scores can be downloaded from the official Eigen page.

**Comment by loof91** [comment]
Perfect, thank you
